name: blazor

on:
  push:
    branches: ["v2"]
    paths: ["apps/blazor/**"]

  pull_request:
    branches: ["v2"]
    paths: ["apps/blazor/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: restore dependencies
        run: dotnet restore ./apps/blazor/FSH.Blazor.sln
      - name: build
        run: dotnet build ./apps/blazor/FSH.Blazor.sln --no-restore
      - name: test
        run: dotnet test ./apps/blazor/FSH.Blazor.sln --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and publish to github container registry
        working-directory: ./apps/blazor/
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/blazor:latest -f Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/blazor:latest
